_wandb:
    value:
        cli_version: 0.23.1
        e:
            7dioxt6osidqv7ncswo1iztkpu0tnvud:
                args:
                    - --aug_mode_dti=mask_edges
                    - --aug_mode_fmri=jitter
                    - --batch_size=16
                    - --dropout=0.5
                    - --dti_drop_prob=0.03972957255665022
                    - --dti_jitter=0.002342097009463845
                    - --embed_dim=16
                    - --epochs=100
                    - --fmri_drop_prob=0.14727179253363346
                    - --fmri_jitter=0.07500039598300906
                    - --gat_heads=4
                    - --gnn_depth=3
                    - --hidden_dim=128
                    - --lr=0.0003
                    - --recon_weight=0
                    - --weight_decay=0.0001
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1966736678912"
                        used: "895446175744"
                email: emanuele.barbieri2@yahoo.it
                executable: /home/emanuele/Desktop/brainSweep/.venv/bin/python
                gpu: AMD Radeon Graphics
                gpu_amd:
                    - id: "1"
                      mclkRange: 0Mhz - 0Mhz
                      model: "0x13c0"
                      performanceLevel: auto
                      sclkRange: 600Mhz - 2200Mhz
                      series: AMD Radeon Graphics
                      sku: RAPHAEL
                      uniqueId: N/A
                      vbiosVersion: 102-RAPHAEL-008
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                    - id: "0"
                      maxPower: "182.0"
                      model: "0x7590"
                      performanceLevel: auto
                      series: AMD Radeon Graphics
                      sku: 44TC6SHB1
                      uniqueId: "0xdebe3b5d819cf9c6"
                      vbiosVersion: 113-44TC6SHB1-P03
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 2
                host: emanuele-X870-EAGLE-WIFI7
                memory:
                    total: "32713289728"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.39
                program: /home/emanuele/Desktop/brainSweep/train.py
                python: CPython 3.12.3
                root: /home/emanuele/Desktop/brainSweep
                startedAt: "2025-12-05T18:49:39.887344Z"
                writerId: 7dioxt6osidqv7ncswo1iztkpu0tnvud
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
aug_mode_dti:
    value: mask_edges
aug_mode_fmri:
    value: jitter
batch_size:
    value: 16
dropout:
    value: 0.5
dti_drop_prob:
    value: 0.03972957255665022
dti_jitter:
    value: 0.002342097009463845
embed_dim:
    value: 16
epochs:
    value: 100
fmri_drop_prob:
    value: 0.14727179253363346
fmri_jitter:
    value: 0.07500039598300906
gat_heads:
    value: 4
gnn_depth:
    value: 3
hidden_dim:
    value: 128
lr:
    value: 0.0003
project_name:
    value: brain-clip-sweep
recon_weight:
    value: 0
weight_decay:
    value: 0.0001
