wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.23450922105511193
dropout:
  value: 0.3
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: clip
lr:
  value: 0.0001
sparsity:
  value: 0.2
