wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.2125573051964932
dropout:
  value: 0.7
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 512
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0.2
