wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.10627212030087492
dropout:
  value: 0.7
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: vicreg
lr:
  value: 0.0005
sparsity:
  value: 0.2
