wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 64
drop_prob:
  value: 0.25764662915869985
dropout:
  value: 0.7
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 512
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0
