wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.10413650491302634
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: vicreg
lr:
  value: 0.0005
sparsity:
  value: 0.2
