wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.3089960137106217
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 1024
loss_type:
  value: clip
lr:
  value: 0.0001
sparsity:
  value: 0.2
