wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.25413114488156174
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 512
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0
