wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 64
drop_prob:
  value: 0.14103208309270351
dropout:
  value: 0.3
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 1024
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0.2
