wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 64
drop_prob:
  value: 0.31317849130952846
dropout:
  value: 0.7
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 1024
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0
