wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 64
drop_prob:
  value: 0.23474634657232787
dropout:
  value: 0.3
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 512
loss_type:
  value: vicreg
lr:
  value: 0.0005
sparsity:
  value: 0.2
