wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 64
drop_prob:
  value: 0.1799313890500323
dropout:
  value: 0.3
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 512
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0
