wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 64
drop_prob:
  value: 0.15540541573214903
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: vicreg
lr:
  value: 0.0001
sparsity:
  value: 0.2
