wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 64
drop_prob:
  value: 0.25486085855850066
dropout:
  value: 0.7
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 1024
loss_type:
  value: vicreg
lr:
  value: 0.0001
sparsity:
  value: 0
