wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.1406142137028718
dropout:
  value: 0.7
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 1024
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0
