wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.39795246103197623
dropout:
  value: 0.7
embed_dim:
  value: 64
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0
