wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 64
drop_prob:
  value: 0.22441223552910416
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
hidden_dim:
  value: 2048
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0
