wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.2530708068501468
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 64
jitter:
  value: 0.07550818888673161
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.001
