wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.17694297061365555
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.02276196585079803
loss_type:
  value: clip
lr:
  value: 0.0003
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.001
