wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.1815704285744839
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 64
jitter:
  value: 0.0381170940578613
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
