wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.2570192833942797
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 32
jitter:
  value: 0.03546388679856941
loss_type:
  value: vicreg
lr:
  value: 0.0003
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
