wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.2843064691324011
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 32
jitter:
  value: 0.010378446133732353
loss_type:
  value: vicreg
lr:
  value: 0.0003
sparsity:
  value: 0.3
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
