wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.32563022802214414
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 64
jitter:
  value: 0.03008254941365532
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
