wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.2871636202474101
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.05446413125051531
loss_type:
  value: hard_neg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
