wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.28268716639353597
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.06135598003150757
loss_type:
  value: hard_neg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 1
use_curriculum:
  value: true
weight_decay:
  value: 0.001
