wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.32352384110980925
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 64
jitter:
  value: 0.07973026010362377
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0.1
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
