wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.12670373157696668
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.04687109529990089
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0.2
tta_steps:
  value: 1
use_curriculum:
  value: true
weight_decay:
  value: 0.001
