wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.2905776034969342
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.01993812746512057
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.001
