wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.33617837920926397
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 32
jitter:
  value: 0.01444580035111422
loss_type:
  value: clip
lr:
  value: 0.0003
sparsity:
  value: 0.3
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.0001
