wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.39153896518104214
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.05490680698927125
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0.3
tta_steps:
  value: 1
use_curriculum:
  value: true
weight_decay:
  value: 0.001
