wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.11290302968595094
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.0677176473141803
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
