wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.3522495449459032
dropout:
  value: 0.6
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 1
hidden_dim:
  value: 32
jitter:
  value: 0.07531448330067098
loss_type:
  value: vicreg
lr:
  value: 0.0003
sparsity:
  value: 0.1
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
