wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.22438295250017937
dropout:
  value: 0.6
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 0.5
hidden_dim:
  value: 64
jitter:
  value: 0.023684464025004973
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.2
tta_steps:
  value: 1
use_curriculum:
  value: true
weight_decay:
  value: 0.0001
