wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.13667508257691743
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 2
hidden_dim:
  value: 32
jitter:
  value: 0.024877940484410985
loss_type:
  value: hard_neg
lr:
  value: 0.001
sparsity:
  value: 0.3
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.001
