wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.10642676948259816
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hard_neg_beta:
  value: 2
hidden_dim:
  value: 32
jitter:
  value: 0.021956813386935947
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0.3
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
