wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.1229049527451331
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.07075696151452147
loss_type:
  value: vicreg
lr:
  value: 0.0005
sparsity:
  value: 0.3
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.0001
