wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.3663100612414581
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 2
hidden_dim:
  value: 32
jitter:
  value: 0.016216303712339973
loss_type:
  value: clip
lr:
  value: 0.001
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.0001
