wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.14552314763981586
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.03780957704864798
loss_type:
  value: clip
lr:
  value: 0.0005
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
