wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.10316318654728986
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 32
jitter:
  value: 0.03948010726404725
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.1
tta_steps:
  value: 1
use_curriculum:
  value: false
weight_decay:
  value: 0.0001
