wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.12378553342110406
dti_jitter:
  value: 0.0342281733192474
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.10582670596806178
fmri_jitter:
  value: 0.04352704992989746
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 64
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
