wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.1452365116857797
dti_jitter:
  value: 0.03452153024522419
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.15942786295316508
fmri_jitter:
  value: 0.0768842260133454
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 128
lr:
  value: 0.0003
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
