wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.15617120338120383
dti_jitter:
  value: 0.0002809860355560134
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.13371614257589431
fmri_jitter:
  value: 0.02261627386458282
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.001
