wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.13309609850416626
dti_jitter:
  value: 0.0279094798488039
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.2310555387153122
fmri_jitter:
  value: 0.03039301788055673
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 32
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.001
