wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.1431814969925352
dti_jitter:
  value: 0.01721035501529545
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.10820845309482324
fmri_jitter:
  value: 0.03111430453304843
gat_heads:
  value: 2
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
