wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.0632515568116232
dti_jitter:
  value: 0.0025016111049352367
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.38871657593796816
fmri_jitter:
  value: 0.07890444528602071
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
