_wandb:
    value:
        cli_version: 0.23.1
        e:
            atmh17lu7twjajlbb4vd5pp5s5d9jt72:
                args:
                    - --aug_mode_dti=jitter
                    - --aug_mode_fmri=mix
                    - --batch_size=16
                    - --dropout=0.6
                    - --dti_drop_prob=0.16358169406429213
                    - --dti_jitter=0.041466680851267
                    - --embed_dim=32
                    - --epochs=100
                    - --fmri_drop_prob=0.35581386897031864
                    - --fmri_jitter=0.06887934329804989
                    - --gat_heads=8
                    - --gnn_depth=2
                    - --hidden_dim=64
                    - --lr=0.0005
                    - --recon_weight=0.5
                    - --weight_decay=1e-05
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1966736678912"
                        used: "895464546304"
                email: emanuele.barbieri2@yahoo.it
                executable: /home/emanuele/Desktop/brainSweep/.venv/bin/python
                gpu: AMD Radeon Graphics
                gpu_amd:
                    - id: "0"
                      maxPower: "182.0"
                      model: "0x7590"
                      performanceLevel: auto
                      series: AMD Radeon Graphics
                      sku: 44TC6SHB1
                      uniqueId: "0xdebe3b5d819cf9c6"
                      vbiosVersion: 113-44TC6SHB1-P03
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                    - id: "1"
                      mclkRange: 0Mhz - 0Mhz
                      model: "0x13c0"
                      performanceLevel: auto
                      sclkRange: 600Mhz - 2200Mhz
                      series: AMD Radeon Graphics
                      sku: RAPHAEL
                      uniqueId: N/A
                      vbiosVersion: 102-RAPHAEL-008
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 2
                host: emanuele-X870-EAGLE-WIFI7
                memory:
                    total: "32713289728"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.39
                program: /home/emanuele/Desktop/brainSweep/train.py
                python: CPython 3.12.3
                root: /home/emanuele/Desktop/brainSweep
                startedAt: "2025-12-05T19:49:06.366271Z"
                writerId: atmh17lu7twjajlbb4vd5pp5s5d9jt72
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
aug_mode_dti:
    value: jitter
aug_mode_fmri:
    value: mix
batch_size:
    value: 16
dropout:
    value: 0.6
dti_drop_prob:
    value: 0.16358169406429213
dti_jitter:
    value: 0.041466680851267
embed_dim:
    value: 32
epochs:
    value: 100
fmri_drop_prob:
    value: 0.35581386897031864
fmri_jitter:
    value: 0.06887934329804989
gat_heads:
    value: 8
gnn_depth:
    value: 2
hidden_dim:
    value: 64
lr:
    value: 0.0005
project_name:
    value: brain-clip-sweep
recon_weight:
    value: 0.5
weight_decay:
    value: 1e-05
