wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.08887349828287001
dti_jitter:
  value: 0.008609107447021841
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.20167816428451807
fmri_jitter:
  value: 0.0890428862160897
gat_heads:
  value: 8
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
