wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.03950895015237084
dti_jitter:
  value: 0.013344200250108336
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3299482016335795
fmri_jitter:
  value: 0.03752438705801307
gat_heads:
  value: 2
gnn_depth:
  value: 3
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
