wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.07400204843843293
dti_jitter:
  value: 0.04029953024452245
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.28973364893635223
fmri_jitter:
  value: 0.0950479746383494
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 64
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
