_wandb:
    value:
        cli_version: 0.23.1
        e:
            top2wll6yw54qx7cc81f71b6ujlma7pe:
                args:
                    - --aug_mode=jitter
                    - --batch_size=16
                    - --drop_prob=0.3750802257600231
                    - --dropout=0.5
                    - --embed_dim=32
                    - --epochs=100
                    - --gat_heads=4
                    - --gnn_depth=1
                    - --hidden_dim=64
                    - --jitter=0.06756307580390811
                    - --loss_type=vicreg
                    - --lr=0.0001
                    - --recon_weight=0.1
                    - --sparsity=0
                    - --weight_decay=0.0001
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1966736678912"
                        used: "895534346240"
                email: emanuele.barbieri2@yahoo.it
                executable: /home/emanuele/Desktop/brainSweep/.venv/bin/python
                gpu: AMD Radeon Graphics
                gpu_amd:
                    - id: "0"
                      maxPower: "182.0"
                      model: "0x7590"
                      performanceLevel: auto
                      series: AMD Radeon Graphics
                      sku: 44TC6SHB1
                      uniqueId: "0xdebe3b5d819cf9c6"
                      vbiosVersion: 113-44TC6SHB1-P03
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                    - id: "1"
                      mclkRange: 0Mhz - 0Mhz
                      model: "0x13c0"
                      performanceLevel: auto
                      sclkRange: 600Mhz - 2200Mhz
                      series: AMD Radeon Graphics
                      sku: RAPHAEL
                      uniqueId: N/A
                      vbiosVersion: 102-RAPHAEL-008
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 2
                host: emanuele-X870-EAGLE-WIFI7
                memory:
                    total: "32713289728"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.39
                program: /home/emanuele/Desktop/brainSweep/train.py
                python: CPython 3.12.3
                root: /home/emanuele/Desktop/brainSweep
                startedAt: "2025-12-08T12:15:46.557757Z"
                writerId: top2wll6yw54qx7cc81f71b6ujlma7pe
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
aug_mode:
    value: jitter
batch_size:
    value: 16
drop_prob:
    value: 0.3750802257600231
dropout:
    value: 0.5
embed_dim:
    value: 32
epochs:
    value: 100
gat_heads:
    value: 4
gnn_depth:
    value: 1
hidden_dim:
    value: 64
jitter:
    value: 0.06756307580390811
loss_type:
    value: vicreg
lr:
    value: 0.0001
project_name:
    value: brain-clip-sweep
recon_weight:
    value: 0.1
sparsity:
    value: 0
vicreg_lambda:
    value: 25
vicreg_mu:
    value: 25
vicreg_nu:
    value: 1
weight_decay:
    value: 0.0001
