_wandb:
    value:
        cli_version: 0.23.1
        e:
            l1wc7ffa9utqb3xp8lp64omrnlm38epl:
                args:
                    - --aug_mode=mix
                    - --batch_size=32
                    - --drop_prob=0.18757153721778955
                    - --dropout=0.4
                    - --embed_dim=64
                    - --epochs=100
                    - --gat_heads=4
                    - --gnn_depth=1
                    - --hard_neg_beta=2
                    - --hidden_dim=128
                    - --jitter=0.0558523392661454
                    - --loss_type=hard_neg
                    - --lr=0.001
                    - --sparsity=0
                    - --tta_steps=5
                    - --use_curriculum=False
                    - --weight_decay=0.001
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1966736678912"
                        used: "904221827072"
                email: emanuele.barbieri2@yahoo.it
                executable: /home/emanuele/Desktop/brainSweep/.venv/bin/python
                gpu: AMD Radeon Graphics
                gpu_amd:
                    - id: "1"
                      mclkRange: 0Mhz - 0Mhz
                      model: "0x13c0"
                      performanceLevel: auto
                      sclkRange: 600Mhz - 2200Mhz
                      series: AMD Radeon Graphics
                      sku: RAPHAEL
                      uniqueId: N/A
                      vbiosVersion: 102-RAPHAEL-008
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                    - id: "0"
                      maxPower: "182.0"
                      model: "0x7590"
                      performanceLevel: auto
                      series: AMD Radeon Graphics
                      sku: 44TC6SHB1
                      uniqueId: "0xdebe3b5d819cf9c6"
                      vbiosVersion: 113-44TC6SHB1-P03
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 2
                host: emanuele-X870-EAGLE-WIFI7
                memory:
                    total: "32713285632"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.39
                program: /home/emanuele/Desktop/brainSweep/train.py
                python: CPython 3.12.3
                root: /home/emanuele/Desktop/brainSweep
                startedAt: "2025-12-09T13:41:30.969192Z"
                writerId: l1wc7ffa9utqb3xp8lp64omrnlm38epl
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 3
                - 14
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
aug_mode:
    value: mix
batch_size:
    value: 32
drop_prob:
    value: 0.18757153721778955
dropout:
    value: 0.4
embed_dim:
    value: 64
epochs:
    value: 100
gat_heads:
    value: 4
gnn_depth:
    value: 1
hard_neg_beta:
    value: 2
hidden_dim:
    value: 128
jitter:
    value: 0.0558523392661454
loss_type:
    value: hard_neg
lr:
    value: 0.001
project_name:
    value: brain-clip-final
sparsity:
    value: 0
tta_steps:
    value: 5
use_curriculum:
    value: false
weight_decay:
    value: 0.001
