wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.0748359995768751
dti_jitter:
  value: 0.0006016747340613082
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.2561762390633393
fmri_jitter:
  value: 0.040170178809740865
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 128
loss_type:
  value: vicreg
lr:
  value: 0.0005
recon_weight:
  value: 0.1
vicreg_lambda:
  value: 50
vicreg_mu:
  value: 50
vicreg_nu:
  value: 5
weight_decay:
  value: 0.0001
