wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.028350357152203888
dti_jitter:
  value: 0.024592798203826895
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.23983785113681408
fmri_jitter:
  value: 0.05576989657696455
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 64
loss_type:
  value: clip
lr:
  value: 0.0005
recon_weight:
  value: 0
vicreg_lambda:
  value: 50
vicreg_mu:
  value: 10
vicreg_nu:
  value: 5
weight_decay:
  value: 0.0001
