wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.029424619309975777
dti_jitter:
  value: 0.03324575581560265
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.17038123670170396
fmri_jitter:
  value: 0.09391719281766071
gat_heads:
  value: 2
gnn_depth:
  value: 3
hidden_dim:
  value: 64
loss_type:
  value: vicreg
lr:
  value: 0.0005
recon_weight:
  value: 0.1
vicreg_lambda:
  value: 25
vicreg_mu:
  value: 50
vicreg_nu:
  value: 5
weight_decay:
  value: 0.0001
