wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.0009313260969996184
dti_jitter:
  value: 0.01734072641620642
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.11563322525709244
fmri_jitter:
  value: 0.03633237380759957
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 128
loss_type:
  value: clip
lr:
  value: 0.0005
recon_weight:
  value: 0.1
vicreg_lambda:
  value: 50
vicreg_mu:
  value: 25
vicreg_nu:
  value: 5
weight_decay:
  value: 0.0001
