wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.1186926484366
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.04105485979715352
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
