wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.1273429617881481
dropout:
  value: 0.4
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 128
jitter:
  value: 0.046753141349945154
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.001
