wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.1232538493331919
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 128
jitter:
  value: 0.06004572070342072
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.001
