wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.27762036187781125
dropout:
  value: 0.6
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.05712566169715394
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
