wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.29848297490340603
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hard_neg_beta:
  value: 1
hidden_dim:
  value: 128
jitter:
  value: 0.05120278996126445
loss_type:
  value: hard_neg
lr:
  value: 0.0005
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
