wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.29099458194058647
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hard_neg_beta:
  value: 1
hidden_dim:
  value: 128
jitter:
  value: 0.03536807600761048
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0.1
tta_steps:
  value: 5
use_curriculum:
  value: true
weight_decay:
  value: 0.0001
