wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.2104586322259008
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.06581642821549342
loss_type:
  value: vicreg
lr:
  value: 0.001
sparsity:
  value: 0
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
