wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.1421043199686948
dti_jitter:
  value: 0.011130587932017362
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14849889962279494
fmri_jitter:
  value: 0.09934365447033366
gat_heads:
  value: 8
gnn_depth:
  value: 4
hidden_dim:
  value: 32
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
