wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.14262524831770443
dti_jitter:
  value: 0.020367602283897415
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.2500014794405876
fmri_jitter:
  value: 0.06449741693564787
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 128
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 1.0e-05
