wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.02502323366638346
dti_jitter:
  value: 0.032873560371716036
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.36306431155375407
fmri_jitter:
  value: 0.03760599312935976
gat_heads:
  value: 2
gnn_depth:
  value: 4
hidden_dim:
  value: 64
lr:
  value: 0.0005
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
