wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.12223874444934348
dti_jitter:
  value: 0.007095021027586041
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3583139485562994
fmri_jitter:
  value: 0.09131137921641248
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
