wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.08374034033121368
dti_jitter:
  value: 0.02870489665075849
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.15931851135286482
fmri_jitter:
  value: 0.09377733139440542
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
