wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.14163629347293588
dti_jitter:
  value: 0.02357086731310433
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.28678422755551713
fmri_jitter:
  value: 0.025476630182169877
gat_heads:
  value: 2
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 1.0e-05
