wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.03322693410649689
dti_jitter:
  value: 0.0013645444494292617
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3050355443441459
fmri_jitter:
  value: 0.05668069908854036
gat_heads:
  value: 8
gnn_depth:
  value: 3
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.001
