wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.1465335709588666
dti_jitter:
  value: 0.03018109680177007
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.39366946242229894
fmri_jitter:
  value: 0.025940913155184167
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0
weight_decay:
  value: 0.001
