wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.18526510188560977
dti_jitter:
  value: 0.04348018335468572
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.2694449632988267
fmri_jitter:
  value: 0.08654684289905094
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
