wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.1113313784645905
dti_jitter:
  value: 0.01838635113396774
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14889033819130043
fmri_jitter:
  value: 0.05402070565586417
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
