wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.16868704209176283
dti_jitter:
  value: 0.0028046998103396117
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3191734576518215
fmri_jitter:
  value: 0.03609161405329217
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 0.001
