wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.11872276891520162
dti_jitter:
  value: 0.014378286454693755
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.15314692037975564
fmri_jitter:
  value: 0.08424617696530994
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.0005
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
