wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.10955466741413494
dti_jitter:
  value: 0.005847448798824074
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.31995659406538246
fmri_jitter:
  value: 0.09172585370191803
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.001
