wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.1872423039216499
dti_jitter:
  value: 0.03359041613197517
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.24017232896993876
fmri_jitter:
  value: 0.024637962345729004
gat_heads:
  value: 8
gnn_depth:
  value: 2
hidden_dim:
  value: 128
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
