wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.05321580295386261
dti_jitter:
  value: 0.025814913582709764
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.20634590502489836
fmri_jitter:
  value: 0.07348805112843403
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 128
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
