wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.11499780873656504
dti_jitter:
  value: 0.004880247346424366
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3087390241305724
fmri_jitter:
  value: 0.0192192524486589
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.001
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
