wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.1764881585303125
dti_jitter:
  value: 0.03934041165393226
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.16028602363650626
fmri_jitter:
  value: 0.06877657670761306
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0.5
weight_decay:
  value: 1.0e-05
