wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.1281452076410094
dti_jitter:
  value: 0.026750030320598257
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.2977837679249229
fmri_jitter:
  value: 0.06235729132112675
gat_heads:
  value: 8
gnn_depth:
  value: 4
hidden_dim:
  value: 32
lr:
  value: 0.0001
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
