wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.11732634938884566
dti_jitter:
  value: 0.003789455444720591
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.17998287842654642
fmri_jitter:
  value: 0.071263927862225
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 32
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 1.0e-05
