wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.18779954673630972
dti_jitter:
  value: 0.027463708872518717
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.13185826868014305
fmri_jitter:
  value: 0.02995958766099935
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
