wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.024423741953910796
dti_jitter:
  value: 0.032560562278397646
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.25986670911315757
fmri_jitter:
  value: 0.08579684716311711
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 64
lr:
  value: 0.0003
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
