wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.004850274322074255
dti_jitter:
  value: 0.03433653999066293
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3827822733585308
fmri_jitter:
  value: 0.09446474690505498
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
