wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.01796129573125933
dti_jitter:
  value: 0.0051753602695203075
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3537500302618585
fmri_jitter:
  value: 0.08110198141241114
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0003
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
