wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.03972957255665022
dti_jitter:
  value: 0.002342097009463845
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14727179253363346
fmri_jitter:
  value: 0.07500039598300906
gat_heads:
  value: 4
gnn_depth:
  value: 3
hidden_dim:
  value: 128
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
