wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.18426119488539888
dti_jitter:
  value: 0.03340984653982518
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.10758490841486212
fmri_jitter:
  value: 0.08168608980989295
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
