wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.17525630004285742
dti_jitter:
  value: 0.03462707129698329
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3468708114818979
fmri_jitter:
  value: 0.023389921482809675
gat_heads:
  value: 8
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
