wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.00210032554269608
dti_jitter:
  value: 0.011241480172548937
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.25488391834199975
fmri_jitter:
  value: 0.09214105683908694
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 0.001
