wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.0005618815446676306
dti_jitter:
  value: 0.01623665534431364
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14810099146031117
fmri_jitter:
  value: 0.023127992072841164
gat_heads:
  value: 8
gnn_depth:
  value: 1
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0
weight_decay:
  value: 0.001
