wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.12273071196293896
dti_jitter:
  value: 0.03489506829241068
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14480561479276716
fmri_jitter:
  value: 0.0600424294932015
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0005
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
