wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.07468309056652625
dti_jitter:
  value: 0.03638039982458005
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3400973196312631
fmri_jitter:
  value: 0.09364920542424382
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0
weight_decay:
  value: 0.001
