wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.07955339872276533
dti_jitter:
  value: 0.034042259757144616
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.15800327349748336
fmri_jitter:
  value: 0.02986706490776958
gat_heads:
  value: 2
gnn_depth:
  value: 3
hidden_dim:
  value: 64
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
