wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.13311867446324346
dti_jitter:
  value: 0.0016337021473395942
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.10301401115883042
fmri_jitter:
  value: 0.05513039853597484
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0003
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
