wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.021500855791189856
dti_jitter:
  value: 0.02070774018296602
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.16559284240735414
fmri_jitter:
  value: 0.08539555801894327
gat_heads:
  value: 8
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 1.0e-05
