wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.12244363984802774
dti_jitter:
  value: 0.00981985259823095
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.397312305502432
fmri_jitter:
  value: 0.08934197247571951
gat_heads:
  value: 8
gnn_depth:
  value: 2
hidden_dim:
  value: 128
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
