wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.06469076109020529
dti_jitter:
  value: 0.03605686851453648
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.10557883299391858
fmri_jitter:
  value: 0.050612571568223325
gat_heads:
  value: 8
gnn_depth:
  value: 2
hidden_dim:
  value: 32
lr:
  value: 0.0003
recon_weight:
  value: 0.5
weight_decay:
  value: 1.0e-05
