wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.16460681404057534
dti_jitter:
  value: 0.046531992199108946
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3850143283162831
fmri_jitter:
  value: 0.04075348914389205
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 64
lr:
  value: 0.0003
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
