wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.0597272274695492
dti_jitter:
  value: 0.02268409719624728
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.184658964149935
fmri_jitter:
  value: 0.020085485705110012
gat_heads:
  value: 8
gnn_depth:
  value: 4
hidden_dim:
  value: 32
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
