wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.009845859078444864
dti_jitter:
  value: 0.04592351547621835
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.30804424913794226
fmri_jitter:
  value: 0.032411889280452306
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 1.0e-05
