wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.02435930007567946
dti_jitter:
  value: 0.021392176171729622
embed_dim:
  value: 64
epochs:
  value: 100
fmri_drop_prob:
  value: 0.1737319781376268
fmri_jitter:
  value: 0.08724449655755823
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
