wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.1979608059259577
dti_jitter:
  value: 0.0054020631708553484
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.203487061899989
fmri_jitter:
  value: 0.03589641978461223
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.0001
recon_weight:
  value: 0.5
weight_decay:
  value: 0.0001
