wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: mix
batch_size:
  value: 32
dropout:
  value: 0.5
dti_drop_prob:
  value: 0.19394517961341792
dti_jitter:
  value: 0.006864257179571182
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.25301819479653276
fmri_jitter:
  value: 0.04931877279122289
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 32
lr:
  value: 0.001
recon_weight:
  value: 0.1
weight_decay:
  value: 0.001
