wandb_version: 1

aug_mode_dti:
  value: mask_edges
aug_mode_fmri:
  value: jitter
batch_size:
  value: 32
dropout:
  value: 0.6
dti_drop_prob:
  value: 0.03957310009074595
dti_jitter:
  value: 0.009895727558579703
embed_dim:
  value: 16
epochs:
  value: 100
fmri_drop_prob:
  value: 0.3050681451897082
fmri_jitter:
  value: 0.07471237083896774
gat_heads:
  value: 4
gnn_depth:
  value: 4
hidden_dim:
  value: 128
lr:
  value: 0.0003
recon_weight:
  value: 0
weight_decay:
  value: 0.0001
