wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: mix
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.029846212924770923
dti_jitter:
  value: 0.024265342006927145
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.19586378712374497
fmri_jitter:
  value: 0.08350152601706248
gat_heads:
  value: 2
gnn_depth:
  value: 4
hidden_dim:
  value: 32
lr:
  value: 0.0005
recon_weight:
  value: 0
weight_decay:
  value: 1.0e-05
