wandb_version: 1

aug_mode_dti:
  value: jitter
aug_mode_fmri:
  value: jitter
batch_size:
  value: 16
dropout:
  value: 0.3
dti_drop_prob:
  value: 0.0407080563543285
dti_jitter:
  value: 0.02357209680355045
embed_dim:
  value: 32
epochs:
  value: 100
fmri_drop_prob:
  value: 0.14473821953629096
fmri_jitter:
  value: 0.04055253125172195
gat_heads:
  value: 8
gnn_depth:
  value: 3
hidden_dim:
  value: 64
lr:
  value: 0.0003
recon_weight:
  value: 0.1
weight_decay:
  value: 0.0001
