wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.3614361653857055
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 32
jitter:
  value: 0.07667282812375739
loss_type:
  value: vicreg
lr:
  value: 0.001
recon_weight:
  value: 0
sparsity:
  value: 0
weight_decay:
  value: 0.001
