wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.11326815133687952
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 32
jitter:
  value: 0.05429639295110061
loss_type:
  value: clip
lr:
  value: 0.0001
recon_weight:
  value: 0
sparsity:
  value: 0.2
weight_decay:
  value: 0.001
