wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.37738047634444294
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.030240868120069875
loss_type:
  value: vicreg
lr:
  value: 0.0005
recon_weight:
  value: 0.1
sparsity:
  value: 0
weight_decay:
  value: 0.001
