wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.34218716980070085
dropout:
  value: 0.5
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.07374266666059788
loss_type:
  value: vicreg
lr:
  value: 0.0005
recon_weight:
  value: 0.1
sparsity:
  value: 0
weight_decay:
  value: 0.0001
