wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 16
drop_prob:
  value: 0.2910875222701905
dropout:
  value: 0.5
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.05146972072837719
loss_type:
  value: vicreg
lr:
  value: 0.0001
recon_weight:
  value: 0.1
sparsity:
  value: 0.1
weight_decay:
  value: 0.0001
