wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.3619276293530973
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 2
hidden_dim:
  value: 32
jitter:
  value: 0.0703501192738571
loss_type:
  value: clip
lr:
  value: 0.0005
recon_weight:
  value: 0.1
sparsity:
  value: 0
weight_decay:
  value: 0.0001
