wandb_version: 1

aug_mode:
  value: jitter
batch_size:
  value: 32
drop_prob:
  value: 0.3250451581687466
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.0317763917894086
loss_type:
  value: vicreg
lr:
  value: 0.0005
recon_weight:
  value: 0.1
sparsity:
  value: 0
weight_decay:
  value: 0.0001
