wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.3328503466733668
dropout:
  value: 0.6
embed_dim:
  value: 32
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.09541511529732576
loss_type:
  value: clip
lr:
  value: 0.001
recon_weight:
  value: 0.1
sparsity:
  value: 0
weight_decay:
  value: 0.0001
