wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 16
drop_prob:
  value: 0.3747416784749523
dropout:
  value: 0.6
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 4
gnn_depth:
  value: 2
hidden_dim:
  value: 64
jitter:
  value: 0.08658976398933516
loss_type:
  value: vicreg
lr:
  value: 0.001
recon_weight:
  value: 0.1
sparsity:
  value: 0.1
weight_decay:
  value: 0.001
