wandb_version: 1

aug_mode:
  value: mix
batch_size:
  value: 32
drop_prob:
  value: 0.15386501226148477
dropout:
  value: 0.4
embed_dim:
  value: 64
epochs:
  value: 100
gat_heads:
  value: 2
gnn_depth:
  value: 1
hard_neg_beta:
  value: 1
hidden_dim:
  value: 64
jitter:
  value: 0.07878464337361508
loss_type:
  value: hard_neg
lr:
  value: 0.001
sparsity:
  value: 0.2
tta_steps:
  value: 5
use_curriculum:
  value: false
weight_decay:
  value: 0.001
